export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_USER_ERRORS = 'GET_USER_ERRORS';
export const LOADING_USER = 'LOADING_USER';
export const LOAD_USER = 'LOAD_USER';
export const UPDATE_CHARLIST = 'UPDATE_CHARLIST';
export const UPDATE_WEAPONLIST = 'UPDATE_WEAPONLIST';
export const UPDATE_MATERIAL = 'UPDATE_MATERIAL';

export const GET_GEN_ERRORS = 'GET_GEN_ERRORS';
export const LOADING_GEN_DATA = 'LOADING_GEN_DATA';
export const LOAD_GEN_DATA = 'LOAD_GEN_DATA';

export const LOADING_REQ = 'LOADING_REQ';
export const GET_REQ_ERRORS = 'GET_REQ_ERRORS';
export const GET_ALL_CHAR_REQ = 'GET_ALL_CHAR_REQ';
export const GET_CHAR_REQ = 'GET_CHAR_REQ';
export const GET_TALENT_REQ = 'GET_TALENT_REQ';
export const GET_ALL_WEAPON_REQ = 'GET_ALL_WEAPON_REQ';
export const GET_WEAPON_REQ = 'GET_WEAPON_REQ';
